import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Clipboard,
  Command,
  Edit,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Lock,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Play,
  Rocket,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: Pizza,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  twitter: Twitter,
  check: Check,
  laptop: Laptop,
  sun: SunMedium,
  moon: Moon,
  // Assessment specific icons
  clipboard: Clipboard,
  edit: Edit,
  rocket: Rocket,
  lock: Lock,
  play: Play,
  clock: Clock
} as const;